vich_uploader:
    db_driver: orm

    mappings:
        monster:
            uri_prefix: /images/monster
            upload_destination: '%kernel.project_dir%/public/images/monster/'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
