vich_uploader:
    db_driver: orm

    mappings:
        monster:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%%app.path.product_images%'
            #uri_prefix: /public/images/monster
            #upload_destination: '%kernel.project_dir%/public/images/monster/'

            inject_on_load: true
            delete_on_update: false
            delete_on_remove: true
